<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SALBTN0" failures="1" tests="4" name="SeleniumWithTestNG.SeleniumWithTestNG.Demo5" time="0.031" errors="0" timestamp="17 Apr 2022 10:56:46 GMT" skipped="1">
  <testcase classname="SeleniumWithTestNG.SeleniumWithTestNG.Demo5" name="loginFunctionality" time="0.024">
    <failure message="expected [abc] but found [login]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [abc] but found [login]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at SeleniumWithTestNG.SeleniumWithTestNG.Demo5.loginFunctionality(Demo5.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginFunctionality -->
  <testcase classname="SeleniumWithTestNG.SeleniumWithTestNG.Demo5" name="homeFunctionality" time="0.000">
    <skipped/>
  </testcase> <!-- homeFunctionality -->
  <testcase classname="SeleniumWithTestNG.SeleniumWithTestNG.Demo5" name="pimFunctionality" time="0.002"/>
  <testcase classname="SeleniumWithTestNG.SeleniumWithTestNG.Demo5" name="logOutFunctionality" time="0.005"/>
</testsuite> <!-- SeleniumWithTestNG.SeleniumWithTestNG.Demo5 -->
